### ISSUE TITLE
Trakt TV API

### ISSUE THREAD

**Issue by adrianmoisey** [rmotr/003-demo-day-tv-show-countdown#10]
Do we want to use [requests](http://www.python-requests.org/en/latest/) or [trakt.py](https://pypi.python.org/pypi/trakt.py/) to talk to the trakt.tv API?

**Comment by Mester** [comment]
Where is the documentation/api for the trakt.py? Our app is pretty simple so requests might be enough, however if that library simplifies things, sure.

**Comment by adrianmoisey** [comment]
Their documentation looks poor. The best I can find is:
https://github.com/fuzeman/trakt.py/blob/master/README.rst
and
https://github.com/fuzeman/trakt.py/tree/master/examples

**Comment by adrianmoisey** [comment]
There also seems to be this one:
https://github.com/moogar0880/PyTrakt
http://pytrakt.readthedocs.org/en/latest/

**Comment by Mester** [comment]
Do you see any functionality that would help getting the countdown? I'm not finding anything that gets the next episode

**Comment by adrianmoisey** [comment]
After playing around with the API and seeing what we will need, I think we should just use `requests`

**Comment by Mester** [comment]
`requests` it is then!
