### ISSUE TITLE
User Session System / Store TV shows in a session

### ISSUE THREAD

**Issue by adrianmoisey** [rmotr/003-demo-day-tv-show-countdown#29]
We're currently just showing individual tv show countdowns.
We should possible have a "search" page and a "my tv shows" page. Doing a search on the search page should allow you to do an "add". This should store your show in a session (https://docs.djangoproject.com/en/1.8/topics/http/sessions/)

The "My tv shows" should have a list of all your tv shows that are stored in the session

**Comment by Mester** [comment]
What do you mean by a search page? A separate to the one we have now?

**Comment by adrianmoisey** [comment]
I think the search page that we have now can stay. We should just move the 'countdown' section to the "my tv shows" page, and make it prettier. We should also have an "add" button next to each search result, which will add the show to the session

**Comment by Mester** [comment]
So `home` is what we have now, only change to search is to add an `add` button, `my tv shows` is just a list of those added shows and then when you click on one of them you go to the countdown page.
Did i understand correctly?

**Comment by adrianmoisey** [comment]
Yes, I think so. I don't mind what the specifics are, but I think the core of what we need is:
- a way to add a tv show to a users session
- a way to display the contents of that session

**Comment by Mester** [comment]
Ok I think I got it.

**Comment by Mester** [comment]
I wouldn't say this is finished yet :P

**Comment by Mester** [comment]
Didn't do the able to click on the listed shows yet
